name: Deploy to Heroku
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: git push
        uses: $GITHUB_REPOSITORY@$GITHUB_HEAD_REF
        run: |
          ls -la
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
